version: '3'

services:
  coffeetalk-mongo-db:
    container_name: coffeetalk-mongo-db
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: ProfileDB

  coffeetalk-service-profile:
    container_name: coffeetalk-service-profile
    image: ctprofile:1.0
    build:
      context: ../
      dockerfile: profile/Dockerfile
    ports:
      - 5000:80
    depends_on:
      - coffeetalk-mongo-db

volumes:
  mongo-data: