apiVersion : apps/v1
kind: Deployment
metadata:
  name: profile 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile 
    spec:
      containers:
        - name: profile 
          image: chris01.azurecr.io/profile
          ports:
          - containerPort: 80